server:
  port: 8081

spring:
  application:
    name: request-processor

  datasource:
    url: jdbc:postgresql://localhost:5432/request_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.flywaydb: DEBUG

outbox:
  batch-size: 50
  delay-ms: 1000